### ISSUE TITLE
Wrong type argument: overlayp, nil

### ISSUE THREAD

**Issue by jsquires** [Overdr0ne/gumshoe#7] opened 2021-12-28 14:30 UTC
I've been trying out gumshoe, and ran into the following error when I execute `gumshoe-backtrack-back` or `gumshoe-backtrack-forward`: 

`gumshoe--replace-footprint: Wrong type argument: overlayp, nil`

I am running Emacs 27.1 in daemon mode on PopOS. 

I was able to avoid the error by configuring the 2 specific options commented below, but obviously this isn't exactly an elegant solution:

```
(use-package gumshoe
  :defer 1 ;; <-- required to avoid the error
  :init (global-gumshoe-mode 1)
  :config (setq gumshoe-show-footprints-p nil)) ;; <-- also required to avoid the error
```

**Comment by Overdr0ne** [comment] 2021-12-29 01:57
Hey there, thanks for taking the time to try this out.

This is a bit tricky, I'm having trouble reproducing the issue with vanilla emacs. You should definitely be able to avoid the error by disabling footprints like you did, but I'm surprised the defer is also required. That error basically means footprints(visual markers associated with each of your previous cursor positions) haven't been populated. Does your cursor jump back to previous positions at least when you call `gumshoe-backtrack-back`? Does `gumshoe-peruse-globally` work for you?

I went ahead and added an extra guard to prevent gumshoe from trying to replace empty footprints, though I'm still not sure why they weren't populated in the first place...

**Comment by jsquires** [comment] 2021-12-29 03:55
Thanks for taking a look at this.

`gumshoe-backtrack-back` (or forward) doesn't move the cursor at all, just generates that error in the *Messages* log each time I invoke it.

`gumshoe-peruse-globally` doesn't generate that error, but only shows 1 option even if I open multiple files and move around in them.

Could this be related to the way emacs initializes in daemon mode (with systemd)?

**Comment by jsquires** [comment] 2021-12-29 13:36
I looked into this a bit more, and narrowed down the issue. It turns out, I was able to reproduce the same behavior in normal (non-daemon) emacs. I commented portions of my config file until I found the culprit:

`(desktop-save-mode 1)`

With that enabled, it seems like gumshoe can't save any backtrack points. If I comment it out, gumshoe seems to work as expected.

Your latest fix did prevent the error message.

**Comment by Overdr0ne** [comment] 2021-12-30 03:31
Wow, thank you for putting in the work to figure that out. Unfortunately, with `(desktop-save-mode 1)`, I have not yet succeeded in reproducing the issue, but I'll continue looking into it.

> gumshoe-peruse-globally doesn't generate that error, but only shows 1 option even if I open multiple files and move around in them.

Could you possibly show me that entry?

Again, really sorry, I'm just still kinda stumped. Desktop-save-mode saves frame parameters and some just a few innocuous globals afaik, unless you've customized it. Do you use customize? It seems gumshoe is starting enough to log at least one entry, but is getting shutdown somehow, or the maybe the post-command-hook that does the logging is getting removed, maybe by desktop-save-mode. Not sure...

**Comment by jsquires** [comment] 2021-12-30 14:44
When I reproduce the issue with your latest change incorporated, gumshoe doesn't seem to generate any entries at all, so `gumshoe-peruse-globally` no longer shows anything.

I have not customized `desktop-save-mode`, just using defaults. If I only leave the following uncommented in my init file, no entries are saved, regardless of movement or opening different files, etc. If I comment the `(desktop-save-mode 1)` line, gumshoe works.

```
(desktop-save-mode 1)

(use-package gumshoe
  :config
  (global-gumshoe-mode t))
```

I realized that just adding `:defer 1` to the use-package above seems to fix everything now, including the overlays, so this is a good enough solution for me. It definitely seems possible there's some sort of conflict between the desktop-save-mode timer and the gumshoe timer, or with how they're initialized, but I don't know enough elisp to dig into it much more.

Other than this issue, gumshoe is working well for me, so thanks for building it!

**Comment by Overdr0ne** [comment] 2021-12-30 18:07
Very happy things are working for you now.

If you are satisfied with things, feel free to ignore future discussion on this thread, you've given me a lot of valuable information already. I will however keep this discussion open for documentation purposes at least, and continue to investigate.

> It definitely seems possible there's some sort of conflict between the desktop-save-mode timer and the gumshoe timer, or with how they're initialized, but I don't know enough elisp to dig into it much more.

So gumshoe logs to the backlog with two independent mechanisms: That timer, but also a command hook that checks the relative cursor position after each command. So for that backlog to be empty, it would mean that both of those mechanisms failed. For both of them to fail, either gumshoe--log-if-necessary is silently failing(unlikely, it's just checking if the ring is empty initially, and other failures would probably trigger errors, and lots of them b/w timers and command hooks triggering constantly), or gumshoe is just not enabled for some reason. That could be because gumshoe--init failed for some reason, or maybe gumshoe-mode got turned off somehow after initially being enabled, which would remove those hooks and the timer. Both of those seem very possible. One likely scenario is, desktop-save-mode is storing the state of global-gumshoe-mode as disabled, so after the gumshoe package loads and enables global-gumshoe-mode, desktop-save-mode then restores the previous state and disables it. The only problem with that theory is, afaik, desktop-save-mode only saves variables in `desktop-globals-to-save`. And I wouldn't think gumshoe--init would fail silently, but I could be wrong, so still not sure here.

If you've read to this point, and you happen to see this issue again, could you check the state of `global-gumshoe-mode` for me?

**Comment by jsquires** [comment] 2021-12-30 20:48
I took a look at my `.emacs.desktop` file, and it had several references to gumshoe mode for the various buffers it was saving. I think it may have been trying to restore those buffers before gumshoe mode was initialized. 

I've modified my config now to delay starting `desktop-save-mode` for a half second, so all other config can execute first, and this seems to work. So now I'm no longer deferring gumshoe mode at all.

**Comment by Overdr0ne** [comment] 2021-12-31 03:04
Oh yes, that makes sense. I hadn't realized desktop-save-mode also saves all minor mode states. That could certainly cause problems, like if for whatever reason global-gumshoe-mode was disabled when desktop-save-mode was activated, it would just restore that state. Or trying to activate global-gumshoe-mode before the use-package definition is evaluated, that could cause parameters evaluated at init to just be ignored. I think your solution is reasonable for now. I wish emacs had the concept of targets like systemd does so you don't have to fiddle with delays. I'm going to close this for now, but just let me know if you notice any other strange interactions with desktop-save-mode here, and I'll reopen it.

**Closed by Overdr0ne** 2021-12-31 03:04 UTC
